services:
  - type: web
    name: telegram-forex-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python attached_assets/bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
